"""Add streak column to user_habits; Remove last_streak_update column from users

Revision ID: 13385189929a
Revises: cba6ef1a5cd6
Create Date: 2025-11-01 06:30:14.698788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13385189929a'
down_revision: Union[str, Sequence[str], None] = 'cba6ef1a5cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_habits', sa.Column('streak', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'user_plans', ['current_plan_id'], ['id'], use_alter=True)
    op.drop_column('users', 'last_streak_update')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_streak_update', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('user_habits', 'streak')
    # ### end Alembic commands ###
