"""Refactored tables

Revision ID: 1d8b0a65938e
Revises: f6d449de60ce
Create Date: 2025-07-25 09:03:12.855082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8b0a65938e'
down_revision: Union[str, Sequence[str], None] = 'f6d449de60ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companions', 'pot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companions', sa.Column('pot', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
