"""Add title column to texts table

Revision ID: 6734abdb69a1
Revises: 8f82157fb6be
Create Date: 2025-10-05 09:09:33.134826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6734abdb69a1'
down_revision: Union[str, Sequence[str], None] = '8f82157fb6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'title')
    # ### end Alembic commands ###
