"""Add level column to accessories to render correctly on frontend

Revision ID: 7d18c0ecd7e3
Revises: e296e981f523
Create Date: 2025-08-08 09:09:07.634924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d18c0ecd7e3'
down_revision: Union[str, Sequence[str], None] = 'e296e981f523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accessories', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accessories', 'level')
    # ### end Alembic commands ###
