"""Update foreign keys in UserPlans and Users

Revision ID: 7d2d574edccb
Revises: c2d46f8c9991
Create Date: 2025-09-16 07:27:27.981907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2d574edccb'
down_revision: Union[str, Sequence[str], None] = 'c2d46f8c9991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
