"""current_plan_id fix - field can be null

Revision ID: 8f68a9fccee3
Revises: 7d2d574edccb
Create Date: 2025-09-16 07:31:41.118862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f68a9fccee3'
down_revision: Union[str, Sequence[str], None] = '7d2d574edccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'current_plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'current_plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
