"""Add saved_learnings table

Revision ID: 8f82157fb6be
Revises: a59af716dec6
Create Date: 2025-10-04 09:47:49.559934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f82157fb6be'
down_revision: Union[str, Sequence[str], None] = 'a59af716dec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_learnings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['learning_id'], ['learnings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'learning_id')
    )
    op.add_column('learnings', sa.Column('tldr', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learnings', 'tldr')
    op.drop_table('saved_learnings')
    # ### end Alembic commands ###
