"""Refacor companion and accessory relationship

Revision ID: a0a2ff99a011
Revises: 1d8b0a65938e
Create Date: 2025-08-07 08:12:34.252562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a2ff99a011'
down_revision: Union[str, Sequence[str], None] = '1d8b0a65938e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companion_accessories', sa.Column('accessory_id', sa.Integer(), nullable=False))
    op.add_column('companion_accessories', sa.Column('shown', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('companion_accessories_accessories_id_fkey'), 'companion_accessories', type_='foreignkey')
    op.create_foreign_key(None, 'companion_accessories', 'accessories', ['accessory_id'], ['id'])
    op.drop_column('companion_accessories', 'accessories_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companion_accessories', sa.Column('accessories_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'companion_accessories', type_='foreignkey')
    op.create_foreign_key(op.f('companion_accessories_accessories_id_fkey'), 'companion_accessories', 'accessories', ['accessories_id'], ['id'])
    op.drop_column('companion_accessories', 'shown')
    op.drop_column('companion_accessories', 'accessory_id')
    # ### end Alembic commands ###
