"""Learnings to Texts and Learnings

Revision ID: a59af716dec6
Revises: ae232b392ead
Create Date: 2025-09-30 17:15:58.406971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59af716dec6'
down_revision: Union[str, Sequence[str], None] = 'ae232b392ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('learning_id', sa.Integer(), nullable=False),
    sa.Column('is_last', sa.Boolean(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['learning_id'], ['learnings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('learnings', 'body')
    op.drop_column('learnings', 'tldr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learnings', sa.Column('tldr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('learnings', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('texts')
    # ### end Alembic commands ###
