"""companion_id is not needed

Revision ID: ae232b392ead
Revises: f814df355ed3
Create Date: 2025-09-16 07:51:47.866828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae232b392ead'
down_revision: Union[str, Sequence[str], None] = 'f814df355ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_plans_companion_id_fkey'), 'user_plans', type_='foreignkey')
    op.drop_column('user_plans', 'companion_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_plans', sa.Column('companion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_plans_companion_id_fkey'), 'user_plans', 'companions', ['companion_id'], ['id'])
    # ### end Alembic commands ###
