"""Add day to Learnings and Tasks

Revision ID: c28a27eb3a1a
Revises: 9098d31368d2
Create Date: 2025-07-18 10:16:02.574241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28a27eb3a1a'
down_revision: Union[str, Sequence[str], None] = '9098d31368d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learnings', sa.Column('day', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('day', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'day')
    op.drop_column('learnings', 'day')
    # ### end Alembic commands ###
