"""Refactor tasks, user_habits and user_tasks tables

Revision ID: f6d449de60ce
Revises: c28a27eb3a1a
Create Date: 2025-07-19 06:02:14.134713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d449de60ce'
down_revision: Union[str, Sequence[str], None] = 'c28a27eb3a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_tasks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'task_id')
    )
    op.drop_table('users_completed_tasks')
    op.add_column('tasks', sa.Column('delayed_xp', sa.Integer(), nullable=False))
    op.drop_column('tasks', 'habit')
    op.add_column('user_habits', sa.Column('last_completed', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_habits', 'last_completed')
    op.add_column('tasks', sa.Column('habit', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'delayed_xp')
    op.create_table('users_completed_tasks',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('users_completed_tasks_task_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users_completed_tasks_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'task_id', name=op.f('users_completed_tasks_pkey'))
    )
    op.drop_table('users_tasks')
    # ### end Alembic commands ###
