"""companion_id in user_plans fix - field can be null

Revision ID: f814df355ed3
Revises: 8f68a9fccee3
Create Date: 2025-09-16 07:48:23.016318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f814df355ed3'
down_revision: Union[str, Sequence[str], None] = '8f68a9fccee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companions', sa.Column('user_plan_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'companions', 'user_plans', ['user_plan_id'], ['id'])
    op.alter_column('user_plans', 'companion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_plans', 'companion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'companions', type_='foreignkey')
    op.drop_column('companions', 'user_plan_id')
    # ### end Alembic commands ###
